Download read and starred items
aminecmi/ReaderforSelfoss pull request #331
Opened 2021-01-11 21:29 UTC by davidoskky

## Types of changes

- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] This is **NOT** translation related. (See [here](https://github.com/aminecmi/ReaderforSelfoss/pull/170#issuecomment-355715654))

This closes issue #305 

The api of selfoss allows loading a maximum of 200 articles at a time. Loading all articles with no filtering allows to get the first 200 articles, but this may fetch no new or starred items if the newest 200 items have all been read already.
In order to make sure to get new and starred icons, we perform 3 calls to the api, one for unread items, one for read items and one for starred items. In this way in the database may be stored up to 600 items at any given time.
All images from these items get cached during the background sync.

2021-01-11 21:39 UTC, aminecmi requested changes

2021-01-11 21:39 UTC, aminecmi commented on app/src/main/java/apps/amine/bou/readerforselfoss/api/selfoss/SelfossService.kt
> +    @GET("items")
This shouldn’t be useful, right ?

2021-01-11 21:39 UTC, aminecmi commented on app/src/main/java/apps/amine/bou/readerforselfoss/HomeActivity.kt
> +                    if (response.body() != null) {
The code inside each on response should be refactored into a function that will be called inside every other on response.

2021-01-11 21:39 UTC, aminecmi commented on app/src/main/java/apps/amine/bou/readerforselfoss/background/background.kt
> +                override fun onFailure(call: Call<List<Item>>, t: Throwable) {
If I’m not mistaking, the code could be refactored here too.

2021-01-11 23:46 UTC, davidoskky commented
I refactored those functions and removed that GET request which I forgot from a previous attempt

2021-01-12 02:55 UTC, aminecmi approved these changes

2021-01-12 02:55 UTC, merged