Date format
aminecmi/ReaderforSelfoss pull request #340
Opened 2021-03-19 16:36 UTC by davidoskky

## Types of changes

- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] This is **NOT** translation related. (See [here](https://github.com/aminecmi/ReaderforSelfoss/pull/170#issuecomment-355715654))

This closes issue #337

Selfoss changed the format of the date. 
With this update they changed api version from 2.21 to 3.0
With this PR the new format should be supported, but I have no way to test it as no version of selfoss with api 3.0 works properly on my server...
It should be tested on selfoss 2.18 as well to make sure that it doesn't break anything...
I tested this on selfoss 2.19 with api 2.21 and everything works fine.

I introduced fetching of the selfoss version from the server and I change the format of the date according to such version.

Do not merge this PR before some testing has been conducted as there may be serious problems in my code.

2021-03-19 17:05 UTC, aminecmi requested changes

2021-03-19 17:05 UTC, aminecmi commented on app/src/main/java/apps/amine/bou/readerforselfoss/utils/ItemsUtils.kt
> +        var date = SimpleDateFormat("yyyy-MM-dd HH:mm:ss").parse(this.datetime)
Is it possible to use the `dateTimeFormatter` variable ?

2021-03-19 17:34 UTC, davidoskky commented on app/src/main/java/apps/amine/bou/readerforselfoss/utils/ItemsUtils.kt
> +        var date = SimpleDateFormat("yyyy-MM-dd HH:mm:ss").parse(this.datetime)
It is possible, but I believe I should pass the version of the api to each item and I don't know if that would be ok.
I could otherwise make the dateTimeFormatter in the Home activity a public variable and then access it from the items, but I'm not sure if that's alrigth as well...

2021-03-19 17:43 UTC, aminecmi commented on app/src/main/java/apps/amine/bou/readerforselfoss/utils/ItemsUtils.kt
> +        var date = SimpleDateFormat("yyyy-MM-dd HH:mm:ss").parse(this.datetime)
Maybe have this a public static field of ˋMyApp` and access it from there ?

2021-03-19 19:54 UTC, davidoskky commented
This should work... it doesn't break anything on api 2.21

2021-03-20 07:10 UTC, davidoskky commented
Sorry about that mess, I drank a bit of wine and didn't realize the ide had changed everything...

2021-03-20 10:26 UTC, aminecmi requested changes

2021-03-20 10:26 UTC, aminecmi commented on app/src/main/java/apps/amine/bou/readerforselfoss/HomeActivity.kt
> +        getApiMajorVersion()
This should also be moved in the `MyApp` class, so it'll change if the version is right.

2021-03-20 10:41 UTC, aminecmi commented
I was already on version "2.21.0", everything was working, and everything still works.

Will try to hava an olver instance to try.

2021-03-21 10:48 UTC, davidoskky commented on app/src/main/java/apps/amine/bou/readerforselfoss/HomeActivity.kt
> +        getApiMajorVersion()
The variable is global, so it can be changed from everywhere in the app.
If you prefer to keep the styling consistent I may move it in MyApp, but I would have to create one `SelfossApi` in MyApp to fetch the version from there.

2021-03-21 11:12 UTC, davidoskky commented
I was able to upgrade to the new version, but the api seems inconsistent: here is the json I get from the api for one object 
`"datetime":{"date":"2021-03-21 10:32:00.000000","timezone_type":3,"timezone":"Europe\/Berlin"}`
I believe the nested entries are what is breaking the dowload of articles, moreover the date format is not the one described in the selfoss docs: `"example": "2013-04-07T13:43:00+01:00"`

2021-03-21 11:15 UTC, aminecmi commented on app/src/main/java/apps/amine/bou/readerforselfoss/HomeActivity.kt
> +        getApiMajorVersion()
Yes, you can do this. This will ensure it is called even if the user isn’t on the home activity when launching the app.

2021-03-21 11:17 UTC, aminecmi commented
I didn’t understand the previous message. What is the datetime object ?

2021-03-21 11:21 UTC, davidoskky commented
It is the datetime of one article when I open /items.
I would expect to get a datetime with a single string containing date, time and timezon but I get three nested values, which as far as I understand is not as it's supposed to be.
I opened this issue https://github.com/fossar/selfoss/issues/1251 as I believe this is a selfoss internal problem.

I will wait for that to be resolved before working more on this.

2021-03-21 13:19 UTC, davidoskky commented
It was in fact an internal selfoss error. This has been corrected and the api version has been bumped to 4.0.
I moved the check for the api version in `MyApp` and I'm storing the version in sharedprefs, so that the correct format will be selected even when offline.

This works on api 4.0, you should check if everything is alright in api 2.21 and selfoss 2.18.

2021-03-22 08:35 UTC, aminecmi commented
The code is ok. I just need to test it on selfoss 2.18.

2021-03-22 12:18 UTC, aminecmi requested changes

2021-03-22 12:18 UTC, aminecmi commented on app/src/main/java/apps/amine/bou/readerforselfoss/MyApp.kt
> +                val version = response.body() as ApiVersion
Just tested it.

Body can be null for older versions.

2021-03-22 12:21 UTC, aminecmi requested changes

2021-03-22 12:21 UTC, aminecmi commented on app/src/main/java/apps/amine/bou/readerforselfoss/MyApp.kt
> +    private fun getApiMajorVersion() {
This isn't called after the first login...

Your solution where you placed it in the HomeActivity was better.

Still, can you place the `dateTimeFormatter` variable inside the `Config` object, and thos api call inside the `HomeActivity` please ?

2021-03-22 17:47 UTC, davidoskky commented
I'm not sure if I correctly understood what you meant by placing the variable in Config; check if this is what you wanted.

2021-03-22 18:00 UTC, aminecmi commented
That’s it, yes.

2021-03-22 18:00 UTC, aminecmi approved these changes

2021-03-22 18:00 UTC, merged