Theme
aminecmi/ReaderforSelfoss pull request #375
Opened 2021-10-29 12:01 UTC by davidoskky

## Types of changes

- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] This is **NOT** translation related. (See [here](https://github.com/aminecmi/ReaderforSelfoss/pull/170#issuecomment-355715654))

I fixed the text colors of the sources pages and simplified the logic here and there using the xml.

2021-10-29 19:25 UTC, aminecmi commented on app/src/main/java/apps/amine/bou/readerforselfoss/SourcesActivity.kt
> +            setTheme(R.style.NoBarDark)
Doesn't this break the theme color selector ?

2021-11-01 20:15 UTC, aminecmi commented
Just tested this.

I see two issues.

## Settings activity does not take the primary and accent colors from the theme itself.

<img width="536" alt="image" src="https://user-images.githubusercontent.com/510304/139735113-3a30a48d-8a3d-45f1-ae37-4ed03517c49c.png">


## Tab bar secondary color isn't refreshed after exciting the settings activity (primary colors change as expected)

(The settings)
<img width="542" alt="image" src="https://user-images.githubusercontent.com/510304/139735477-5485ebe2-ee43-4766-8cfd-fb67c81841db.png">

(The colors without refreshing the app)
<img width="536" alt="image" src="https://user-images.githubusercontent.com/510304/139735525-1eebffb2-6083-4783-923b-35f8e05c0bcf.png">

2021-11-01 20:16 UTC, aminecmi requested changes
Needs changing to handle secondary color issues, and theme activity issue.

2021-11-01 22:20 UTC, davidoskky commented
I see the issue, I'll fix this after working on #376

2021-11-21 22:46 UTC, davidoskky commented
The settings now uses the selected colors.
The colors selected are applied after leaving the settings page.
I'm unable to apply them while in the settings...

2021-11-22 19:46 UTC, aminecmi commented
@davidoskky There is still one last issue.

<img width="538" alt="image" src="https://user-images.githubusercontent.com/510304/142925265-bf768c28-3b9c-4f80-98e8-9bffb57b4bdc.png">

The source title and time in dark theme are unreadable as they are in black.

2021-11-23 18:31 UTC, davidoskky commented
Right, I didn't notice that before.
This is now solved as well.

2021-11-29 19:26 UTC, merged