Restructure code architecture
aminecmi/ReaderforSelfoss pull request #409
Opened 2022-02-13 15:41 UTC by davidoskky

## Types of changes

- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] This is **NOT** translation related. (See [here](https://github.com/aminecmi/ReaderforSelfoss/pull/170#issuecomment-355715654))

I've been reading some stuff about android development and I'm restructuring the code to see if I understood what I read.
In this restructuring I'm moving all the api calls, database managment and most logical operations to SharedItems in order to simplify the code in activities and fragments.
SharedItems remains a singleton, but it's initiated through dependency injection so that it's independent of any activity, this should help solving problems such as #263.
The resulting code should be easier to test, as almost everything to be tested should be contained within SharedItems.
Api and database should be easier to mock, in order to test the code in unit tests.
I'll be adding this mock after I finished transfering all the functionalities.

This whole restructure should not provide any significant advantage to the end user, it might speed up api requests as now all of those will be in coroutines.

2022-02-13 16:20 UTC, davidoskky commented
Thanks.

I'll keep contributing if you move to multiplatform, however I don't have an iPhone so I won't be able to test those functionalities.
Let me know if you find things which could be done better, I'm still moving functions around but the architecture should stay as it is.
I just read a bit of stuff and I'm in no way an expert. thus I guess many things could be done better.
(I wanted to make SharedItems a viewmodel but wasn't able to... the way it's implemented however should work well anyways.)

2022-02-13 18:56 UTC, aminecmi commented
> I'll keep contributing if you move to multiplatform, however I don't have an iPhone so I won't be able to test those functionalities.

Great ! I'll handle IOS testing, no worries. Thanks for the work you do on the app !

2022-02-23 22:46 UTC, davidoskky commented
I feel this is a good point for reviewing what I've done, I feel this is quite a lot to review.
The architecture is in place even though most of the logic still has to be moved from the activities and fragments.
All API calls and database interaction is handled by SharedItems, most of the data is propagated through stateflows.
I put in place a preliminary fake of the repository for testing and added a few unit tests, these do not need an Android emulator and thus are very quick to run.
The testing is there just to make sure that this approach works, however the structure of the FakeRepository should be improved to find a better way to structure all the tests.

Previous tests are currently broken, I'm not fixing those yet in view of further restructuring in the next PRs.

Future objectives are:
- Moving all the logical operation to SharedItems
- Implementing tests for all the functions in SharedItems

2022-03-07 09:10 UTC, aminecmi requested changes

2022-03-07 09:10 UTC, aminecmi commented on app/src/main/java/apps/amine/bou/readerforselfoss/utils/LinksUtils.kt
> +        //SharedItems.position = currentItem
Could you remove this commented code please ?

2022-03-07 14:30 UTC, davidoskky commented on app/src/main/java/apps/amine/bou/readerforselfoss/HomeActivity.kt
> -    private fun getApiMajorVersion() {
I moved this to SharedItems.
I didn't get around removing that try catch as it was involved somewhere I didn't want to edit immediately.
Indeed everything will rely on the api version and not on a catch.

I'm currently not using Config.apiVersion as I would have to inject Config somewhere and I first wanted to figure out the best place.
If you prefer, I can figure this out directly in this PR, so that we don't introduce any misleading code.

2022-03-10 19:04 UTC, aminecmi commented on app/src/main/java/apps/amine/bou/readerforselfoss/HomeActivity.kt
> -    private fun getApiMajorVersion() {
>  If you prefer, I can figure this out directly in this PR, so that we don't introduce any misleading code.

Yes please.

2022-03-10 19:05 UTC, aminecmi commented
No problem @davidoskky
Take your time.

2022-04-03 22:13 UTC, davidoskky commented
Here it is
Using the app I noticed that this refactor solves #357 for some reason

2022-04-04 13:53 UTC, aminecmi commented
Hi @davidoskky 

thanks for your changes. I won’t merge them yet, since I’m in the process if moving to a Kotlin multi platform project, and I hade to change a lot of code. 

I’ll be able to push everything in one or two weeks, and I’ll try to save the project history and branches on there too.

2022-05-22 11:42 UTC, closed without merging